routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\ProductController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Initial View Controller
 */
Route::get('/',
    [ProductController::class, 'index']
)->name('home');

/**
 * Orders
 */
Route::get('/checkout/{id}',
	[ProductController::class, 'formCheckout']
)->name('checkout');

Route::get('/show',
	[OrderController::class, 'show']
)->name('show');
Route::get('/order-list',
	[OrderController::class, 'index']
)->name('order-list');
Route::get('/order-details/{id}',
	[OrderController::class, 'details']
)->name('order-details');


Route::resource('/order', OrderController::class);

resources/views/checkout.blade.php
@extends('template')
@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-10">
                <h2 class="mb-3">ORDENES</h2>
            </div>
            <div class="col-md-2">
                <a class="btn btn-outline-success"
                    href="{{ route('checkout',2) }}">
                    Listado de Ordenes
                </a>
            </div>
        </div>

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="container mt-5">
            <form class="needs-validation" action="{{ route('order.store') }}" method="POST">
                @csrf
                <input type="hidden" name='product_id' value="{{ $product->id }}">
                <input type="hidden" name='total' value="{{ $product->price }}">
                <div class="form-row">
                    <H5 for="inputname">DATOS PERSONALES</H5>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-5">
                        <label for="name">Nombre:</label>
                        <input type="text" class="form-control" name="customer_name" placeholder="Ingrese su nombre"  required>
                    </div>
                    <div class="form-group col-md-4">
                        <label for="mail">Email</label>
                        <input type="email" class="form-control" name="customer_email" placeholder="Email" required>
                    </div>
                    <div class="form-group col-md-3">
                        <label for="mobile">Telefono:</label>
                        <input type="number" class="form-control" name="customer_mobile" placeholder="+54 999 999-8888" required>
                    </div>
                </div>
                <div class="form-row">&nbsp;</div>
                <div class="form-row">
                    <H5 for="inputname">DATOS DE REFERENCIA</H5>
                </div>
                <div class="form-row">
                    <div class="form-group col-md-7">
                        <label for="inputProduct">Producto:</label>
                        <input type="text" class="form-control" name="inputProduct" placeholder="Product Name" value="{{ $product->name }}" disabled>
                    </div>
                    <div class="form-group col-md-5">
                        <label for="inputPrice">Precio ($):</label>
                        <input type="text" class="form-control" name="inputPrice" placeholder="Price" value="{{ $product->price }}" disabled>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary">PAGAR LA ORDEN</button>
              </form>
        </div>
    </div>
</div>

@endsection

resources/views/orderdetails.blade.php
@extends('template')
@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="row box-part text-center">
            <div class="col-md-12">
                <h2 class="mb-3">Estado de la Compra</h2>
            </div>
        </div>
        <div class="col-md-12">
            <div class="box-part text-center">
                <div style="font-size: 10rem">
                    @if($orders[0]->status == 'FAILED' || $orders[0]->status == 'REJECTED')
                        <i class="bi bi-x-circle text-danger"></i>
                    @elseif($orders[0]->status == 'CREATED' || $orders[0]->status == 'PENDING')
                        <i class="bi bi-exclamation-circle text-warning"></i>
                    @elseif($orders[0]->status == 'APPROVED')
                        <i class="bi bi-check2-circle text-success"></i>
                    @endif
                </div>
                <div class="title">
                    <h4>{{ $orders[0]->status }}</h4>
                </div>
                <div class="col-md-12 text-center">
                    <h6 class="card-title"><strong>Referencia:</strong> {{$orders[0]->reference}}</h6>
                </div>
                <div class="col-md-12 text-center">
                    <h6 class="card-title"><strong>Total:</strong> ${{number_format($orders[0]->total)}}</h6>
                </div>
                <div class="col-md-12 text-center">
                    <h6 class="card-title"><strong>Fecha transacción:</strong>
                        {{ date('d-m-Y', strtotime($orders[0]->created_at))}}
                </div>
                @if($orders[0]->status == 'REJECTED')
                    <a href="{{$orders[0]->url}}">Intentar el pago nuevamente</a>
                @endif
                @if ($orders[0]->status == 'PENDING')
                    <a href="{{$orders[0]->url}}">Verificar Pago</a>
                    &nbsp;&nbsp;&nbsp;|
                @endif
                <a href="{{ route('order-list') }}">&nbsp;&nbsp;&nbsp;Volver al Listado</a>
             </div>
        </div>
    </div>
</div>

@endsection

resources/views/orderlist.blade.php
@extends('template')
@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-10">
                <h2 class="mb-3">Listado de Ordenes</h2>
            </div>
            <div class="col-md-2">
                <a class="btn btn-outline-success"
                    href="{{ route('home') }}">
                    Volver al Inicio
                </a>
            </div>
        </div>

        <div class="container mt-5">
            <table class="table table-bordered mb-5">
                <thead>
                    <tr class="table-success text-center">
                        <th scope="col">#</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Email</th>
                        <th scope="col">Telefono</th>
                        <th scope="col">Producto</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Total</th>
                        <th scope="col">Acción</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($orders as $data)
                    <tr>
                        <th scope="row" class="text-center">{{ $data->id }}</th>
                        <td>{{ $data->customer_name }}</td>
                        <td>{{ $data->customer_email }}</td>
                        <td>{{ $data->customer_mobile }}</td>
                        <td>{{ $data->name }}</td>
                        <td style="text-align: center">
                            @if($data->status == 'FAILED' || $data->status == 'REJECTED')
                                <span class="badge badge-danger">
                                    {{ $data->status }}
                                </span>
                            @elseif($data->status == 'CREATED' || $data->status == 'PENDING')
                                <span class="badge badge-warning">
                                    {{ $data->status }}
                                </span>
                            @elseif($data->status == 'APPROVED')
                                <span class="badge badge-success">
                                    {{ $data->status }}
                                </span>
                            @endif
                        </td>
                        <td class="text-center">${{number_format($data->total)}}</td>
                        <td class="text-center">
                            <a class="btn btn-outline-primary"
                                href="{{ route('order-details', $data->order_id) }}">
                                Detalles
                            </a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
            {{-- Pagination --}}
            <div class="d-flex justify-content-center">
                {!! $orders->links() !!}
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/payment.blade.php
@extends('template')
@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="row box-part text-center">
            <div class="col-md-12">
                <h2 class="mb-3">Estado de la Compra</h2>
            </div>
        </div>

        <div class="col-md-12">
            <div class="box-part text-center">
                <div style="font-size: 10rem">
                    @if($result->status->status == 'FAILED' || $result->status->status == 'REJECTED')
                        <i class="bi bi-x-circle text-danger"></i>
                    @elseif($result->status->status == 'CREATED' || $result->status->status == 'PENDING')
                        <i class="bi bi-exclamation-circle text-warning"></i>
                    @elseif($result->status->status == 'APPROVED')
                        <i class="bi bi-check2-circle text-success"></i>
                    @endif
                </div>
                <div class="title">
                    <h4>{{ $result->status->status }}</h4>
                </div>
                <div class="col-md-12 text-center confir-block-descrip">

                    <h6 class="card-title"><strong>Estado:</strong> {{$result->status->message}}</h6>
                </div>
                <div class="col-md-12 text-center">
                    <h6 class="card-title"><strong>Referencia:</strong> {{$transac->reference}}</h6>
                </div>
                <div class="col-md-12 text-center">
                    <h6 class="card-title"><strong>Total:</strong> ${{number_format($order->total)}}</h6>
                </div>
                <div class="col-md-12 text-center">
                    <h6 class="card-title"><strong>Fecha transacción:</strong>
                        {{ date('d-m-Y', strtotime($transac->created_at))}}
                </div>
                @if($result->status->status == 'REJECTED')
                    <a href="{{$transac->url}}">Intentar el pago nuevamente</a>
                @endif
                @if ($result->status->status == 'PENDING')
                    <a href="{{$transac->url}}">Verificar Pago</a>
                @endif
                &nbsp;&nbsp;&nbsp;|
                <a href="{{ route('home') }}">&nbsp;&nbsp;&nbsp;Volver al inicio</a>
             </div>
        </div>
    </div>
</div>

@endsection

resources/views/template.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Listado de Productos - PlaceToPay</title>
    <title>Laravel Pagination Demo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">

<!------ Include the above in your HEAD tag ---------->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body class="bg-light">
    <div class="container">
        <div class="py-5 text-justify">
                @yield('content')
        </div>
    </div>
</body>

</html>